install: true
cache:
  directories:
    - .build/checkouts # SwiftPM
    - .build/repositories # SwiftPM
branches:
  only:
    - master
matrix:
  include:
    - name: "Swift Test"
      os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - swift test
      env:
        - JOB=CI_UNIT_TEST
    - name: "Swiftlint"
      os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - swiftlint version
        - swiftlint
      env:
        - JOB=CI_SWIFTLINT
    - name: "Generate Xocde Coverage"
      os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - swift package generate-xcodeproj
        - xcodebuild -scheme xcodemissing -enableCodeCoverage YES build test -quiet
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      env:
        - JOB=CI_CODE_COVERAGE
