install: true
cache:
  directories:
    - .build/checkouts # SwiftPM
    - .build/repositories # SwiftPM
branches:
  only:
    - master
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - swift test
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - swiftlint version
        - swiftlint
