install: true
cache:
  directories:
    - .build/checkouts # SwiftPM
    - .build/repositories # SwiftPM
branches:
  only:
    - master
matrix:
  include:
    - name: "Swift Test"
      os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - make test
    - name: "Swiftlint"
      os: osx
      language: objective-c
      osx_image: xcode10.2
      script:
        - make lint
